"use client";
import {useEffect,useRef,useState} from "react";
import {Heart,MapPin,Play,Sparkles} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Textarea} from "@/components/ui/textarea";
const photos=Array.from({length:15},(_,i)=>`/memories/photo-${String(i+1).padStart(2,"0")}.jpg`);
const vids=Array.from({length:2},(_,i)=>`/videos/video-${String(i+1).padStart(2,"0")}.mp4`);
const reasons=["Your caring heart","The comfort I feel with you","The way you speak","Your patience with me","The nights you stayed on call","Every ordinary day you made special","The way I can share anything","Simply—you"];
function Counter(){const[elapsed,setElapsed]=useState(0);useEffect(()=>{const start=new Date("2025-12-29T18:00:00+05:30").getTime();const tick=()=>setElapsed(Math.max(0,Date.now()-start));tick();const t=window.setInterval(tick,1000);return()=>window.clearInterval(t)},[]);const a=[[Math.floor(elapsed/864e5),"days"],[Math.floor(elapsed/36e5)%24,"hours"],[Math.floor(elapsed/6e4)%60,"minutes"],[Math.floor(elapsed/1e3)%60,"seconds"]];return <div className="counter" suppressHydrationWarning>{a.map(([v,l])=><div key={l}><b>{String(v).padStart(2,"0")}</b><span>{l}</span></div>)}</div>}
function Memory({src,n}:{src:string,n:number}){const[ok,setOk]=useState(true);return ok?<img className="photo" src={src} alt={`Memory ${n}`} onError={()=>setOk(false)}/>:<div className="photo placeholder"><Heart/><span>Add photo-{String(n).padStart(2,"0")}.jpg</span></div>}
const collageStart=[
  [5,8,20,-7],[30,5,24,5],[62,7,20,-4],[78,23,18,8],[8,39,22,4],
  [35,32,19,-9],[57,38,23,6],[73,52,21,-6],[4,68,20,7],[27,63,23,-3],
  [52,67,18,9],[76,72,20,3],[17,18,17,10],[45,15,17,-5],[64,24,17,4],
  [38,50,18,-2],[58,55,18,7]
];
function MemoryDeck(){const stage=useRef<HTMLDivElement>(null);const[spots,setSpots]=useState(()=>collageStart.map((p,i)=>({x:p[0],y:p[1],w:p[2],r:p[3],z:i+1})));const drag=useRef<{i:number,x:number,y:number,sx:number,sy:number}|null>(null);const items=[...photos.map((src,i)=>({type:"photo",src,n:i+1})),...vids.map((src,i)=>({type:"video",src,n:i+1}))];const down=(e:React.PointerEvent<HTMLElement>,i:number)=>{if((e.target as HTMLElement).tagName==="VIDEO")return;const max=Math.max(...spots.map(s=>s.z))+1;setSpots(s=>s.map((p,j)=>j===i?{...p,z:max}:p));drag.current={i,x:e.clientX,y:e.clientY,sx:spots[i].x,sy:spots[i].y};e.currentTarget.setPointerCapture(e.pointerId)};const move=(e:React.PointerEvent<HTMLElement>)=>{if(!drag.current||!stage.current)return;const rect=stage.current.getBoundingClientRect(),d=drag.current;const nx=Math.max(0,Math.min(100-spots[d.i].w,d.sx+(e.clientX-d.x)/rect.width*100)),ny=Math.max(0,Math.min(76,d.sy+(e.clientY-d.y)/rect.height*100));setSpots(s=>s.map((p,i)=>i===d.i?{...p,x:nx,y:ny}:p))};const stop=()=>{drag.current=null};return <><div className="drag-hint">✦ PICK UP AND DRAG ANY FRAME · 15 PHOTOS + 2 VIDEOS</div><div ref={stage} className="throwback-wall">{items.map((item,i)=>{const p=spots[i];return <article className="throwback-card" key={item.type+item.src} style={{left:`${p.x}%`,top:`${p.y}%`,width:`${p.w}%`,zIndex:p.z,transform:`rotate(${p.r}deg)`}} onPointerDown={e=>down(e,i)} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}><span className="drag-grip">⋮⋮ {item.type==="photo"?`MEMORY ${String(item.n).padStart(2,"0")}`:`VIDEO ${String(item.n).padStart(2,"0")}`}</span>{item.type==="photo"?<Memory src={item.src} n={item.n}/>:<video src={item.src} muted loop playsInline controls aria-label={`Memory video ${item.n}`}/>}</article>})}</div></>}
export default function Home(){const[love,setLove]=useState(72),[caught,setCaught]=useState(0),[pos,setPos]=useState({x:50,y:48});const catchHeart=()=>{setCaught(c=>c+1);setPos({x:8+Math.random()*80,y:12+Math.random()*70})};return <main>
<nav><span className="brand">S <Heart size={14} fill="currentColor"/> A</span><div><a href="#story">Our story</a><a href="#memories">Memories</a><a href="#game">A little game</a></div></nav>
<section className="hero"><div className="stars"/><div className="hero-copy"><p className="eyebrow">31 · 08 · 2026 / FOR ANSHU</p><h1>Happy birthday<br/><em>to my favourite person.</em></h1><p className="lead">Some people arrive quietly, then become the most beautiful part of every day. This is our story—still being written.</p><a className="primary" href="#story"><Play size={16} fill="currentColor"/> Begin our story</a></div><div className="orbit"><div className="globe"><span>29.12.25</span></div><div className="orbit-line"/><p>Mahabalipuram<br/><small>12°37′59.62″N · 80°11′46.46″E</small></p></div><div className="scroll-note">SCROLL TO REMEMBER ↓</div></section>
<section id="story" className="section story"><p className="kicker">WHERE IT ALL BEGAN</p><h2>One evening by the sea.</h2><div className="first-meet"><div className="date-card"><span>DEC</span><b>29</b><small>2025 · Evening</small></div><div><h3>Mahabalipuram, Tamil Nadu</h3><p>At those exact coordinates, we met for the first time. We did not know that a simple meeting would become daily conversations, comfort, laughter, arguments, and a bond I never want to lose.</p></div></div><div className="map-card"><iframe title="Route from IIT BHU to Raj Ghat, Varanasi" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?output=embed&saddr=IIT+(BHU),+Varanasi&daddr=Raj+Ghat,+Varanasi"/><div className="map-heading"><span>VARANASI · OUR EVERYDAY JOURNEY</span><b><MapPin/> IIT (BHU) <Heart fill="currentColor"/> Raj Ghat</b><small>Two places, one journey—made every day with care.</small></div></div><div className="letter"><Sparkles/><p>“You came from Raj Ghat to meet me, and I came from IIT(BHU) to meet you. Somewhere between those journeys, friendship quietly became love.”</p></div></section>
<section className="section dark-section"><p className="kicker">EVERY SECOND SINCE WE MET</p><h2>Our story has no end date.</h2><Counter/><p className="waiting">Friendship keeps growing. Love keeps waiting—gently, honestly, without an ending.</p></section>
<section id="memories" className="section memories"><p className="kicker">LITTLE PIECES OF US</p><h2>Our throwbacks.</h2><p className="intro">Fifteen photos and two videos, scattered like real memories. Pick up any framed moment and place it wherever you want.</p><MemoryDeck/></section>
<section className="section promise"><div><p className="kicker">WHAT I COULDN'T ALWAYS SAY</p><h2>I love you, Anshu.</h2></div><div className="promise-copy"><p>I love your character, your caring nature, the way you speak, and the comfort I feel when I am with you. With you, I want to share everything without thinking twice.</p><p>We have fought many times, yet you stayed. When nights felt uncomfortable, you stayed on video call. I may not understand why you never left—but I never take your presence for granted.</p><p>I know you did not accept my proposal, and I respect your feelings and your choice. This website is not pressure; it is simply my honest way of saying that I care deeply. I am still here, still grateful, and still waiting—with patience and respect.</p><span>— Sairam</span></div></section>
<section id="game" className="section game-section"><p className="kicker">A SILLY LITTLE DAILY SMILE</p><h2>Catch my heart!</h2><p className="intro">Tap the floating heart. Every catch reveals one more reason you are special to me.</p><div className="game-board"><button className="floating-heart" style={{left:`${pos.x}%`,top:`${pos.y}%`}} onClick={catchHeart}>❤</button><div className="score">HEARTS CAUGHT <b>{caught}</b></div><div className="reason">{caught?reasons[(caught-1)%reasons.length]:"Catch the heart to begin…"}</div></div></section>
<section className="section questions"><div><p className="kicker">YOUR SIDE OF OUR STORY</p><h2>Now I want to listen.</h2><p>Your answers matter to me. Be completely honest—there is no right answer and no pressure.</p></div><form action="https://formsubmit.co/mudavath.sairam.apd22@itbhu.ac.in" method="POST"><input type="hidden" name="_subject" value="Anshu replied to the birthday website 💌"/><input type="hidden" name="_captcha" value="false"/>{[["Why she stays","What makes you stay with me, even after our fights?"],["What she likes","What is one thing you genuinely like about me?"],["What I should improve","What do you not like in me, or want me to improve?"],["Favourite memory","Which memory of us makes you smile most?"],["What I mean to her","In your own words, what am I to you?"],["Her message","A message you want to leave for me"]].map(([n,q])=><label key={n}>{q}<Textarea name={n} required={n!=="Favourite memory"&&n!=="Her message"}/></label>)}<label>How much love is there in your heart for me? <b>{love}%</b><input type="range" name="Love percentage" min="0" max="100" value={love} onChange={e=>setLove(+e.target.value)}/></label><Button type="submit" className="submit">Send your heart to Sairam <Heart fill="currentColor"/></Button></form></section>
<footer><Heart fill="currentColor"/><h2>Happy Birthday, Anshu.</h2><p>Wherever this story goes, thank you for being one of the most meaningful parts of my life.</p><small>MADE WITH LOVE · 31 AUGUST 2026</small></footer>
</main>}
